version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"  # Porta do Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permite que o Portainer se comunique com o Docker
      - portainer_data:/data  # Persistência dos dados do Portainer

volumes:
  portainer_data:  # Cria um volume persistente para os dados do Portainer
